dist: trusty
os: linux

language: node_js

node_js:
  - "10.9"

addons:
  chrome: stable

cache:
  directories:
    - "./node_modules"
    - "~/.npm"
    - ".jest"

env:
  - FRONTEND=AdminClient/
  - FRONTEND=RepClient/

#stages:
#  - test
##  - name: deploy
##    if: branch = master

#Test stage
# This needs to be the default stage due to build Matrix
before_install: cd $FRONTEND
script: npm run test -- --no-watch --no-progress --code-coverage=true --browsers=ChromeHeadlessCI
after_success: npx codecov
