dist: trusty
os: linux

env:
  - FRONTEND=AdminClient/
  - FRONTEND=RepClient/

language: node_js
node_js:
  - "10.9"

services:
  - docker

addons:
  chrome:
    stable

cache:
  directories:
    - "./node_modules"
    - "~/.npm"
    - ".jest"

before_install: cd $FRONTEND

stages:
  - test
  - coverage
#  - name: deploy
#    if: branch = master

test:
    script: npm run test -- --no-watch --no-progress --code-coverage=true --browsers=ChromeHeadlessCI

coverage:
  before_script:
  script: npx codecov
