dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome:
    stable

cache:
  directories:
    - ./node_modules

before_script: cd ./RepClient

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --code-coverage=true --browsers=ChromeHeadlessCI
