dist: trusty
os: linux

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
cache:
  directories:
    - "./node_modules"
    - "$HOME/.npm"
    - ".jest"
    - "$HOME/.m2"
jobs:
  include:
    - name: Admin Client Frontend Tests
      language: node_js
      node_js:
        - "12.16.3"
      before_install: cd AdminClient/
      script:
        # - npm run e2e_headless # Ignore this for now as it wont run
        - npm run test -- --no-watch --no-progress --code-coverage=true --browsers=ChromeHeadlessCI
      after_success: npx codecov
    - name: Rep Client Frontend Tests
      language: node_js
      node_js:
        - "12.16.3"
      before_install: cd RepClient/
      script: npm run test:travis
      after_success: npx codecov
    - name: Backend Tests
      language: java
      jdk:
        - openjdk8
      before_install: cd Backend/


