dist: trusty
sudo: true

language: node_js
node_js:
  - "10.9"

addons:
  chrome:
    stable

cache:
  directories:
    - ./node_modules

before_install:
  - ls -a
  - cd RepClient/
  - ls -a
install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --code-coverage=true --browsers=ChromeHeadlessCI
