dist: trusty
os: linux

env:
  - FRONTEND=AdminClient/
  - FRONTEND=RepClient/

language: node_js

node_js:
  - "10.9"

addons:
  chrome: stable

cache:
  directories:
    - "./node_modules"
    - "~/.npm"
    - ".jest"

before_install: cd $FRONTEND

stages:
  - test
  - coverage
#  - name: deploy
#    if: branch = master

jobs:
  include:
    - stage: test
      script: npm run test -- --no-watch --no-progress --code-coverage=true --browsers=ChromeHeadlessCI
    - stage: coverage
      before_script: skip
      script: npx codecov
