trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Backend/*
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: Maven@3
    inputs:
      mavenPomFile: 'Backend/pom.xml'
      goals: 'clean verify'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: Docker@2
    inputs:
      containerRegistry: 'omegacr'
      repository: 'dev-backend'
      command: 'buildAndPush'
      Dockerfile: './Backend/Dockerfile'
      buildContext: './Backend'
      tags: |
        latest
        $(Build.BuildId)

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-prod'
      namespace: 'default'
      command: 'apply'
      arguments: '-f ./Devops/k8s/backend/'



  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-default'
      namespace: 'default'
      command: 'apply'
      arguments: '-f ./Devops/k8s/backend/'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-default'
      namespace: 'default'
      command: 'set'
      arguments: 'image deployment/backend-deployment2 backend2-api=omegacr.azurecr.io/dev-backend:$(Build.BuildId)'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-prod'
      namespace: 'default'
      command: 'set'
      arguments: 'image deployment/backend-deployment2 backend2-api=omegacr.azurecr.io/dev-backend:$(Build.BuildId)'
