trigger:
  branches:
    include:
      - master
      - refs/tags/be*
    exclude:
      - refs/tags/c1*
      - refs/tags/c2*
  paths:
    include:
    - /Backend/*


pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: Maven@3
    inputs:
      mavenPomFile: 'Backend/pom.xml'
      goals: 'clean verify'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: Docker@2
    inputs:
      containerRegistry: 'omegacr'
      repository: 'prod-backend'
      command: 'buildAndPush'
      Dockerfile: './Backend/Dockerfile'
      buildContext: './Backend'
      tags: |
        latest
        $(Build.BuildId)



  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-default'
      namespace: 'production'
      command: 'apply'
      arguments: '-f ./Devops/k8s/backend/'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-default'
      namespace: 'production'
      command: 'set'
      arguments: 'image deployment/backend-deployment2 backend2-api=omegacr.azurecr.io/prod-backend:$(Build.BuildId)'

  - task: Kubernetes@1
    inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'OmegaCluster-prod'
        namespace: 'production'
        command: 'apply'
        arguments: '-f ./Devops/k8s/backend/'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-prod'
      namespace: 'production'
      command: 'set'
      arguments: 'image deployment/backend-deployment2 backend2-api=omegacr.azurecr.io/prod-backend:$(Build.BuildId)'
