apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'frontend-deployment'
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend-adminclient
          image: omegacr.azurecr.io/dev-frontend
          ports:
            - containerPort: 4200
          env:
            - name: GIT_COMPANY
              valueFrom:
                secretKeyRef:
                  name: frontend
                  key: window.env.company
            - name: API_ROOT
                valueFrom:
                  secretKeyRef:
                    name: frontend
                    key: window.env.apiRoot
