apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster

  selector:
    component: frontend
  ports:
    - port: 80
      targetPort: 4200
