apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster

  selector:
    component: backend2
  ports:
    - port: 80
      targetPort: 5000
      name: http
    - port: 3306
      targetPort: 3306
      name: mysql