apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'frontend-deployment'
spec:
  replicas: 5
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend-adminclient
          image: omegacr.azurecr.io/dev-frontend
          ports:
            - containerPort: 4200